export const PLANS = {
  FREE: {
    id: 'free',
    name: 'Básico',
    price: 0,
    currency: '€',
    period: 'mes',
    subtitle: 'Para individuos que están comenzando.',
    features: [
      'Estudios ilimitados',
      'Participantes propios ilimitados',
      'Transcripción básica con marcas de tiempo',
      'Soporte básico - respuesta en menos de 48h',
      'Sin funciones de IA',
      'Sin segmentos demográficos',
      'RGPD - Alojado en la UE',
    ],
  },
  STARTER: {
    id: 'starter',
    name: 'Starter',
    price: 49,
    currency: '€',
    period: 'mes',
    subtitle: 'Para equipos pequeños que necesitan transcripción de IA y soporte prioritario.',
    features: [
      'Estudios ilimitados',
      'Participantes propios ilimitados',
      '5 participantes incluidos/mes',
      'Transcripción con marcas de tiempo con IA',
      'Soporte priortario - respuesta en menos de 24h',
      'Sin segmentos demográficos',
      'RGPD - Alojado en la UE',
    ],
  },
  PRO: {
    id: 'pro',
    name: 'Pro',
    price: 99,
    currency: '€',
    period: 'mes',
    subtitle: 'Para equipos que necesitan segmentación y soporte más rápido.',
    features: [
      'Estudios ilimitados',
      'Participantes propios ilimitados',
      'Extracción de insights con IA',
      '10 participantes incluidos/mes',
      'Transcripción por entrada de análisis con IA',
      'Segmentos demográficos para orientación de participantes',
      'Soporte prioritario - respuesta en menos de 8h',
      'RGPD - Alojado en la UE',
    ],
  },
};